use PolyGlotPlanet;

insert into Lingua values
("AZ", "azerbaigiano", 24, "img/stati/azerbaigian.svg"),
("BE", "bielorusso", 7.9, "img/stati/bielorussia.svg"),
("BG", "bulgaro", 8.3, "img/stati/bulgaria.svg"),
("BS", "bosniaco", 1.8,"img/stati/bosnia.svg"),
("CA", "catalano", 5.3, "img/stati/catalogna.svg"),
("CS", "ceco", 10.7, "img/stati/cechia.svg"),
("CY", "gallese", 0.5, "img/stati/galles.svg"),
("DA", "danese", 6.1, "img/stati/danimarca.svg"),
("DE", "tedesco", 76.6, "img/stati/germania.svg"),
("EL", "greco", 13.1, "img/stati/grecia.svg"),
("EN", "inglese", 369.9, "img/stati/uk.svg"),
("ES", "spagnolo", 471.4, "img/stati/spagna.svg"),
("ET", "estone", 1.4, "img/stati/estonia.svg"),
("EU", "basco", 0.5, "img/stati/euskadi.svg"),
("FI", "finlandese", 5.5, "img/stati/finlandia.svg"),
("FO", "faroense", 0.08, "img/stati/isole_far_oer.svg"),
("FR", "francese", 79.6, "img/stati/francia.svg"),
("GA", "irlandese", 1.7, "img/stati/irlanda.svg"),
("HR", "croato", 5.5, "img/stati/croazia.svg"),
("HU", "ungherese", 12.6, "img/stati/ungheria.svg"),
("HY", "armeno", 6.3, "img/stati/armenia.svg"),
("IS", "islandese", 0.3, "img/stati/islanda.svg"),
("IT", "italiano", 64.8, "img/stati/italia.svg"),
("JA", "giapponese", 126.3, "img/stati/giappone.svg"),
("KA", "georgiano", 3.9,"img/stati/georgia.svg"),
("KO", "coreano", 82, "img/stati/corea_del_sud.svg"),
("LT", "lituano", 2.5, "img/stati/lituania.svg"),
("LV", "lettone", 2.1,"img/stati/lettonia.svg"),
("MK", "macedone", 3.5, "img/stati/macedonia_del_nord.svg"),
("NL", "olandese", 23.1, "img/stati/paesi_bassi.svg"),
("NO", "norvegese", 4.2, "img/stati/norvegia.svg"),
("PL", "polacco", 39.7, "img/stati/polonia.svg"),
("PT", "portoghese", 232.4, "img/stati/portogallo.svg"),
("RO", "rumeno", 25.1, "img/stati/romania.svg"),
("RU", "russo", 153.7, "img/stati/russia.svg"),
("SK", "slovacco", 5.4, "img/stati/slovacchia.svg"),
("SL", "sloveno", 2.6, "img/stati/slovenia.svg"),
("SQ", "albanese", 1.2, "img/stati/albania.svg"),
("SR", "serbo", 6.3, "img/stati/serbia.svg"),
("SV", "svedese", 9, "img/stati/svezia.svg"),
("TR", "turco", 82.2, "img/stati/turchia.svg"),
("UK", "ucraino", 27.3, "img/stati/ucraina.svg"),
("ZH", "cinese", 921.1, "img/stati/cina.svg"),
("AF", "afrikaans", 6.8, "img/stati/sudafrica.svg"),
("HI", "hindi", 342.2, "img/stati/india.svg");